/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Teas', [{
      name: 'Ассам',
      image: 'https://avatars.mds.yandex.net/get-mpic/5209712/img_id1220860871838156647.jpeg/orig',
      description: 'Сорт чёрного крупнолистового чая, выращиваемого на северо-востоке Индии, в долине реки Брахмапутры, между Шиллонгом и Восточными Гималаями.',
      country_id: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Си Ху Лун Цзин',
      image: 'http://livey-internet.alloy.ru/media/cache/d0/04/d0045b91fe5dc3487048b1cad82bbfe9.jpg',
      description: 'Разновидность зелёного чая из Ханчжоу, провинция Чжэцзян, Китай. Изготовляется, как правило, вручную, вследствие чего цена на этот сорт выше по сравнению с большинством сортов. Отмечен почётным титулом Знаменитый чай Китая.',
      country_id: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Да хун пао',
      image: 'https://taketea.ru/wp-content/uploads/f/3/8/f38d87013287fe7b03d6b42d9de8bb7c.jpeg',
      description: '«Большой Красный Халат», утёсный китайский чай, который производят на северо-западе провинции Фуцзянь, в горах Уи. По классу его относят к улунам средней ферментации или полуферментированным улунам.',
      country_id: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Санпин-ча',
      image: 'https://about-tea.ru/wp-content/uploads/1/7/7/177a41b3baf62d20e19e90d691ac2c98.jpeg',
      description: 'Это самый популярный чай Окинавы – смесь зеленого чая и цветов жасмина.',
      country_id: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Молочный чай вьетнамский',
      image: 'https://about-tea.ru/wp-content/uploads/a/2/0/a20c8bfd8022525d7688971b6ee11587.jpeg',
      description: 'Этот напиток содержит в своем составе антиоксиданты, йод, кальций, магний и фосфор. Его употребления способствует профилактике заболеваний сердечнососудистой системы, помогает избавиться от кожных болезней и сбросить лишние килограммы.',
      country_id: 5,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Оолонг (Улун)',
      image: 'https://opolzeivrede.ru/wp-content/uploads/2020/01/oolongl.jpg',
      description: 'Чай с богатым витаминным составом. Форма, цвет, вкус, аромат и свойства бирюзовых экстрактов различаются в зависимости от погодных условий, способа культивирования и обработки. Высокое качество оолонга, чудесный неподражаемый аромат и благотворное воздействие на организм обеспечиваются уникальным климатом высокогорья, где сама природа научила людей полуферментировать чайные растения.',
      country_id: 6,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Чай с колендулой (Цветочный)',
      image: 'https://znaychay.ru/wp-content/uploads/2020/05/chaj-iz-kalenduly.jpg',
      description: 'Упоминание о его полезных свойствах встречается еще в рукописях 12 века. Уже тогда календулу использовали для снятия жара, лечения болезней мочеполовых органов.',
      country_id: 7,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Тесс',
      image: 'https://dostavka-produktov.ru/image/cache/catalog/products_images/3451439-900x900.jpg',
      description: 'Это великолепный черный чай, который был создан из чайных листьев, выращенных вблизи экватора на высокогорных плантациях Кении. Насыщенный и крепкий, с глубоким вкусом и ярким настоем, он идеально сочетается с молоком.',
      country_id: 8,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Хиссон',
      image: 'https://prochayok.ru/wp-content/uploads/2019/07/3-upakovki-chaya-hajson.jpg',
      description: 'Марка имеет различные сертификаты, подтверждающие высокое качество чая. Например, Хайсон удостоен знаком «Золотой Лев», который выдается Чайным советом Шри-Ланки и гарантирует подлинность плантационного цейлонского чая.',
      country_id: 9,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Мятный Гуаяса',
      image: 'https://mixsp.ru/files/011/0110847edbf9ce8495410f6f3a1261c8.jpg',
      description: 'Из-за высокого содержания эфирных масел в листьях (1-2,5%), особенно ментола, мятный чай популярен благодаря своим лечебным свойствам. Считается, что он оказывает противовоспалительное действие, влияя на пищеварительную систему и выведение желудочного сока.',
      country_id: 10,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Лимонный чай',
      image: 'https://cdn-asset.jawapos.com/wp-content/uploads/2019/11/ginger_flickr_cc-Dailycal.jpg',
      description: 'Витамин С в лимоне обладает мощными антиоксидантными и противовоспалительными свойствами. Это помогает иммунитету бороться с инфекциями и защищает организм от окислительного стресса окружающей среды.',
      country_id: 11,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Мате',
      image: 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Mate_en_calabaza.jpg',
      description: 'Напиток из высушенных и измельчённых листьев падуба парагвайского или так называемого падуба тернистого, или кустистого (Ilex dumosa).',
      country_id: 12,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Mate cocido',
      image: 'https://d2j6dbq0eux0bg.cloudfront.net/images/31730034/2807205675.jpg',
      description: 'Это напиток с горьким вкусом, похожий на мате , но более мягкий, с такими же стимулирующими и питательными свойствами. Он также продается в пакетиках, поэтому его можно заваривать как чай.',
      country_id: 13,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Ломанный чай',
      image: 'https://uley-shop.ru/wp-content/uploads/Ivan-chay-chernyy-1.jpg',
      description: 'Очень необычный чай',
      country_id: 14,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Pайз',
      image: 'https://images.wbstatic.net/big/new/33870000/33878706-1.jpg',
      description: 'Укрепляет почки и мочеполовую систему, обладает мочегонным действием',
      country_id: 15,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Угандский чай',
      image: 'https://www.tearoad.ru/wp-content/uploads/2017/10/1-58.jpg',
      description: 'В экваториальной Уганде чай, бесспорно, является национальным напитком. Он также служит, наряду с хлопком и кофе, главной статьей экспорта.',
      country_id: 16,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Оранж Пеко',
      image: 'https://tea-world.net/images/t/388//images/goods-item/906/images/16-5c8.jpg',
      description: 'Темный как истинный уроженец Африки. Знойный как солнце над Саванной. Крепкий и насыщенный Оранж Пеко черный из Руанды.  Редкий гость в магазинах в чистом виде.',
      country_id: 17,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Бурундийский чай',
      image: 'https://about-tea.ru/wp-content/uploads/b/3/6/b36f7cd0c1d795f7f38ab1aacc152322.jpeg',
      description: 'Бурундийский чай – редкий напиток, который обладает своеобразным интенсивным вкусом и высоко ценится мировыми экспертами за непосредственный профиль.',
      country_id: 18,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Малавийский чай',
      image: 'https://www.tea.moscow/teaimages/postimg/images/2013_07_17_14_001.jpg',
      description: 'Aфриканские чаи из Малави – это чаи черные, с резковатым вкусом и отличной экстрактивностью.',
      country_id: 19,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Ройбуш',
      image: 'https://mrfilin.com/wp-content/uploads/d/c/6/dc6f9f6dfcaf23dcf56f375c4b7be867.jpe',
      description: 'Tравяной чай из листьев-игл и стеблей куста семейства бобовых. Растение прихотливо, культивации вне Южной Африки не поддается.',
      country_id: 20,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Ройбуш кокосовый',
      image: 'https://chay.ru/img/products/thumbs/800x600/r.07_kokosovyj.jpg',
      description: 'Содержит большое количество антиоксидантов и витаминов, а также богатый минеральныйсостав. Укрепляет нервную систему, повышает активность мозга.',
      country_id: 21,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Чай Мозамбик Organic',
      image: 'https://chay.ru/img/products/thumbs/800x600/r.07_kokosovyj.jpg',
      description: 'Черный чай сильной скрутки OP1 Organic. Произведен в Республике Мозамбик (Африка) и сертифицирован как органический продукт согласно европейским требованиям.',
      country_id: 22,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Танзайнийский чай',
      image: 'http://www.novostioede.ru/upload/iblock/c31/chaj.jpg',
      description: 'Употребление чая довольно широко распространено среди местного населения. Пьют чай обычно с вскипяченным молоком и горячим.',
      country_id: 23,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Черный чай с добавками Мадагаскар Guste',
      image: 'https://ir.ozone.ru/s3/multimedia-3/wc1000/6364005939.jpg',
      description: 'Чёрный чай, изюм, цукаты папайи и ананаса.',
      country_id: 24,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Маврикийский чай',
      image: 'http://www.novostioede.ru/upload/iblock/33d/029.jpg',
      description: 'В целом маврикийский чай производится по традиционной технологии и обладает приемлемым качеством. Его особенность – ванильный аромат. Он довольно насыщен, хорошо сочетается с молоком. Идеален для завтрака.',
      country_id: 25,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Майский чай',
      image: 'https://metropolis-online.ru/upload/iblock/c15/c15ed9166f65a77e3f3fc0f11cb0588d.jpg',
      description: 'Pеализуется индийский чай среднеценового сегмента. Чаеразвесочная фабрика расположена во Фрязино Московской области.',
      country_id: 26,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Акбар',
      image: 'https://s.myspar.ru/upload/img/10/1066/106692.jpg?1592316452',
      description: 'Марка чая, принадлежащая компании Akbar Brothers Ltd. Компания основана на Цейлоне в 1907 г. семьей Акбаралли. Шри-Ланка производит более 300 тысяч тонн чая, что составляет примерно 22% от мирового производства.',
      country_id: 27,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Непальский чай черный крупнолистовой',
      image: 'https://avatars.mds.yandex.net/get-mpic/6479667/img_id508808659308474685.jpeg/orig',
      description: 'Непальский черный чай очень богат витаминами, он понижает риск развития рака желудка, кишечника, даже рака молочной железы. Борется с лишним весом, выводит шлаки и токсины из организма, укрепляет иммунитет.',
      country_id: 28,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Чай чёрный Maharaja Tea Assam Dikom',
      image: 'https://avatars.mds.yandex.net/get-mpic/5042167/img_id6782405857032431148.jpeg/orig',
      description: 'Этот чай называют правильным благородным ассамом - не очень крупный, хорошо скрученный, имеет много типсов, тёмный настой и ожидаемая терпкость.',
      country_id: 29,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Чай Бангладеш',
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Sreemangal_tea_garden_2017-08-20.jpg/2560px-Sreemangal_tea_garden_2017-08-20.jpg',
      description: 'Чай выращивается в северных и восточных районах, высокогорье, умеренный климат, влажность и обильные осадки в этих районах создают благоприятные условия для производства высококачественного чая.',
      country_id: 30,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      name: 'Чай Принцесса Ява Премиум Улун',
      image: 'https://www.tea-coffee.ru/teaphoto/coffee22818.jpeg',
      description: 'Напиток с уникальными вкусовыми характеристиками, так как к стандартным травяным ноткам в нем добавляется изысканная горчинка. Сырье для его производства собирают на плантациях Индонезии, известных своей экологической чистотой.',
      country_id: 31,
      createdAt: new Date(),
      updatedAt: new Date(),
    }], {});
  },
  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Teas', null, {});
  },
};
